# Generated by Django 3.0.6 on 2020-06-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('rented', models.BooleanField()),
                ('equipment', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Renters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.Apartments')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.Apartments')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.Renters')),
            ],
        ),
    ]
