# Generated by Django 3.0.6 on 2020-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
