# Generated by Django 3.0.7 on 2020-06-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hirers',
            new_name='Renters',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='hirer',
            new_name='renter',
        ),
    ]
