# Generated by Django 3.0.6 on 2020-06-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0002_auto_20200623_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='rented',
        ),
    ]
