# Generated by Django 3.0.6 on 2020-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0003_remove_apartments_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(),
        ),
    ]
