# Generated by Django 3.0.6 on 2020-06-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0005_examplepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentsPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.Apartments')),
            ],
        ),
    ]
