# Generated by Django 3.0.6 on 2020-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0006_apartmentspics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentsRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='surface',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='rooms',
            field=models.ManyToManyField(null=True, to='handling.ApartmentsRooms'),
        ),
    ]
