# Generated by Django 3.0.6 on 2020-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0007_auto_20200624_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='rooms',
            field=models.ManyToManyField(to='handling.ApartmentsRooms'),
        ),
    ]
