# Generated by Django 3.0.6 on 2020-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0009_auto_20200624_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
