# Generated by Django 3.0.6 on 2020-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0010_apartments_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='costs',
            field=models.IntegerField(null=True),
        ),
    ]
