# Generated by Django 3.0.6 on 2020-06-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0011_apartments_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renters',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handling.Apartments'),
        ),
    ]
