# Generated by Django 3.0.6 on 2020-06-30 14:11

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0012_auto_20200626_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentspics',
            name='pics',
            field=smartfields.fields.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='examplepic',
            name='model_pic',
            field=smartfields.fields.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
