# Generated by Django 3.0.6 on 2020-06-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0013_auto_20200630_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentspics',
            name='pics',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='examplepic',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
